// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoL6cjFGU17U_Cpkn0K8RCyPAA_uQJyVg',
    appId: '1:489285071816:web:58596a75c71bc93130c6fd',
    messagingSenderId: '489285071816',
    projectId: 'lab3-c8cca',
    authDomain: 'lab3-c8cca.firebaseapp.com',
    storageBucket: 'lab3-c8cca.firebasestorage.app',
    measurementId: 'G-5N05PJN2FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlQBaN8zE7rYR85wIWldXGXsttYKrbW0',
    appId: '1:489285071816:android:6b5103c0cfa69f6230c6fd',
    messagingSenderId: '489285071816',
    projectId: 'lab3-c8cca',
    storageBucket: 'lab3-c8cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXcIbgpTwldnQX7qIfDlssOBy0_juOAM',
    appId: '1:489285071816:ios:3e9f3cff0b3a12bd30c6fd',
    messagingSenderId: '489285071816',
    projectId: 'lab3-c8cca',
    storageBucket: 'lab3-c8cca.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZXcIbgpTwldnQX7qIfDlssOBy0_juOAM',
    appId: '1:489285071816:ios:3e9f3cff0b3a12bd30c6fd',
    messagingSenderId: '489285071816',
    projectId: 'lab3-c8cca',
    storageBucket: 'lab3-c8cca.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoL6cjFGU17U_Cpkn0K8RCyPAA_uQJyVg',
    appId: '1:489285071816:web:7c8754304bc4cf6b30c6fd',
    messagingSenderId: '489285071816',
    projectId: 'lab3-c8cca',
    authDomain: 'lab3-c8cca.firebaseapp.com',
    storageBucket: 'lab3-c8cca.firebasestorage.app',
    measurementId: 'G-MCKXXWK0LD',
  );
}
